services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - devploy-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: DevPloyDB
    networks:
      - devploy-network

volumes:
  postgres-data:

networks:
  devploy-network:
    driver: bridge
