services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./access.log:/usr/src/app/access.log
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - devploy-network
      - traefik-public
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.devploy-api.rule=Host(`api.devploy.dev`)'
      - 'traefik.http.routers.devploy-api.tls=true'
      - 'traefik.http.services.devploy-api.loadbalancer.server.port=3000'

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: DevPloyDB
    networks:
      - devploy-network
    labels:
      - "traefik.enable=false"

volumes:
  postgres-data:

networks:
  devploy-network:
    driver: bridge
  traefik-public:
    external: true
