version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: DevPloyDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
