version: '3.3'
secrets:
  cf-token:
    file: ./traefik/cf-token
services:
  traefik:
    image: 'traefik:v3.3.4'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - traefik-public
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf-token
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './access.log:/var/log/traefik/access.log'
      - './traefik/traefik.yaml:/traefik.yaml:ro'
      - './traefik/acme.json:/acme.json'
      - './traefik/config.yaml:/config.yaml:ro'
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.devploy.dev`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.devploy.dev`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=devploy.dev"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.devploy.dev"
      - "traefik.http.routers.traefik-secure.service=api@internal"

volumes:
  traefik-log:

networks:
  traefik-public:
    external: true
