version: '3.3'

services:
  traefik:
    image: 'traefik:v3.3.4'
    command:
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.swarm
      - --providers.swarm.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.docker.network=traefik-public
      - --api
      - --api.dashboard=true
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --accesslog.format=json
    ports:
      - '80:80'
      - '443:443'
    networks:
      - traefik-public
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './access.log:/var/log/traefik/access.log'
      - './traefik/certs:/etc/certs'
      - './traefik/cert-trarfik.yaml:/etc/traefik/dynamic/cert-trarfik.yaml'
    deploy:
      labels:
        # Dashboard
        - 'traefik.enable=true'
        # Change the host url here
        - 'traefik.http.routers.traefik.rule=Host(`traefik.devploy.dev`)'
        - 'traefik.http.routers.traefik.tls=true'
        - 'traefik.http.routers.traefik.service=api@internal'
        - 'traefik.http.services.traefik.loadbalancer.server.port=8080'

volumes:
  traefik-log:

networks:
  traefik-public:
    external: true
